### PR TITLE
Program C to find Keyword in a Text File!

### PR DESCRIPTION
**Pull request by MAYANK25402**
Hey!  I want you to please add this program to your repository as it covers the concept of File Handling.

Thank You!

### CODE REVIEW

**Comment by fennecdjay** [comment]
I can't figure out why this would be useful to add or what the purpose is, so I'll close this for now. Feel free to elaborate in comments if you disagree.

btw, there a typo in the txt file, `voltile` should read `volatile`

**Comment by forrcaho** [comment]
Looks like we've got our first Hacktoberfest spam PR. This submitter made basically the same PR to something like a dozen projects. [According to DigialOcean](https://hacktoberfest.digitalocean.com/resources)

>  Spammy pull requests can be labeled as “spam” or "invalid."
> 
> Maintainers are faced with the majority of spam that occurs during Hacktoberfest, and we dislike spam just as much as you.
> 
> If you're a maintainer, please label any spammy pull requests submitted to the repositories you maintain as ‘spam’ or ‘invalid’, and close them.
> 
> Pull requests with a label containing either of these words won't count toward Hacktoberfest. 

I didn't see how to label a PR, but this one needs a 'spam' label.

**Comment by forrcaho** [comment]
Ok, I figured it out, now we have a "spam" label we can mark these sorts of PRs with in the future. Here's hoping we don't have to!

**Comment by MAYANK25402** [comment]
This shows your mentality! 

I am right now laughing at you how fool such people can be.

No worries Have a Good Day so called maintainer!

**Comment by MAYANK25402** [comment]
If it was a spam there could be a small changes but I provided you a code in C which explains a simple program and have a concept of File Handling.

**Comment by fennecdjay** [comment]
Great work, thank you so much.

**Pull request closed without merging**
